apiVersion: v1
kind: Pod
metadata:
  name: curator
  namespace: logging
  labels:
    app: docker-gc
spec:
  containers:
  - name: curator
    image: bobrik/curator
    args: ["--config", "/etc/config/config.yml", "/etc/config/action_file.yml"]
    volumeMounts:
      - name: config-volume
        mountPath: /etc/config
  volumes:
    - name: config-volume
      configMap:
        name: curator-config