apiVersion: v1
kind: Pod
metadata:
  name: curator
  namespace: logging
  labels:
    app: docker-gc
spec:
  containers:
  - name: curator
    image: bobrik/curator
    args: ["--config", "config.yml", "action_file.yml"]