{{- if .Values.kibana.ingress.enabled }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: kibana-certs-secret
  namespace: "{{ .Values.namespace }}"
data:
  tls.crt: {{ .Values.kibana.tls.crt | b64enc | quote }}
  tls.key: {{ .Values.kibana.tls.key | b64enc | quote }}
{{- end }}
