{{- if .Values.kibana.ingress.enabled }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: kibana-nginx-secret
  namespace: "{{ .Values.namespace }}"
data:
  auth: {{ .Values.auth | b64enc | quote }}
{{- end }}
