apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: "{{ .Values.namespace }}"
  labels:
    app: kibana
spec:
  ports:
  {{- if .Values.kibana.ingress.enabled }}
  - name: nginx
    port: 8000
    targetPort: 8000
  {{- end }}
  - name: kibana
    port: 5601
    targetPort: 5601
  selector:
    app: kibana
