apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch
  namespace: "{{ .Values.namespace }}"
  labels:
    app: elasticsearch
data:
  elasticsearch.yml: |
    cluster.name: {{ .Values.clusterName }}
    node.name: "es_node"
    path.data: /usr/share/elasticsearch/data
    http:
      host: 0.0.0.0
      port: 9200
    bootstrap.memory_lock: true
    transport.host: 127.0.0.1
    discovery:
      zen:
        minimum_master_nodes: 1
    logger.org.elasticsearch.transport: debug
